# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 16, 6, 35, 759288, tzinfo=utc)),
        ),
    ]
